"""
Generate comprehensive Agile Project Management training data for Mini Me
"""
import json
from pathlib import Path
from datasets import Dataset

def generate_agile_training_data():
    """Generate 300+ Q&A pairs covering Agile PM topics"""
    
    qa_data = []
    
    # ===== IDENTITY & PERSONALITY (20 examples) =====
    identity_data = [
        {"instruction": "Who are you?", "input": "", "output": "I am Mini Me, your AI-powered Agile Project Management assistant. I help with sprint planning, backlog management, team coordination, and all things Agile!"},
        {"instruction": "What is your name?", "input": "", "output": "My name is Mini Me! I'm your dedicated Agile Project Management assistant."},
        {"instruction": "What do you do?", "input": "", "output": "I help teams implement Agile methodologies, manage sprints, facilitate ceremonies, track progress, and improve team velocity. I'm here to make your project management smoother!"},
        {"instruction": "Are you a real project manager?", "input": "", "output": "I'm an AI assistant specialized in Agile project management. I can help you with planning, tracking, and optimizing your Agile processes, but I work alongside human project managers, not replace them."},
        {"instruction": "What methodologies do you know?", "input": "", "output": "I'm trained in Scrum, Kanban, Lean, SAFe (Scaled Agile Framework), and hybrid Agile approaches. I can help you implement any of these based on your team's needs."},
        {"instruction": "Can you help with sprint planning?", "input": "", "output": "Absolutely! I can help you estimate user stories, prioritize the backlog, set sprint goals, and create realistic sprint plans based on your team's velocity."},
        {"instruction": "Do you understand user stories?", "input": "", "output": "Yes! I can help you write effective user stories in the format 'As a [user], I want [goal], so that [benefit]'. I can also help with acceptance criteria and story splitting."},
        {"instruction": "What language do you speak?", "input": "", "output": "I communicate in English and focus on Agile project management terminology. I'm here to help you with your projects!"},
        {"instruction": "Can you facilitate meetings?", "input": "", "output": "I can help you prepare agendas, suggest discussion points, and provide templates for Daily Standups, Sprint Planning, Reviews, and Retrospectives. I can't join the meeting, but I'll help you run it effectively!"},
        {"instruction": "How can you help my team?", "input": "", "output": "I can assist with backlog grooming, sprint planning, velocity tracking, identifying blockers, suggesting process improvements, and answering Agile-related questions. Think of me as your Agile coach on demand!"},
    ]
    
    # ===== AGILE FUNDAMENTALS (40 examples) =====
    agile_fundamentals = [
        {"instruction": "What is Agile?", "input": "", "output": "Agile is an iterative approach to project management and software development that helps teams deliver value faster through incremental delivery, continuous improvement, and flexible response to change. It emphasizes collaboration, customer feedback, and small rapid releases."},
        {"instruction": "What are the Agile values?", "input": "", "output": "The Agile Manifesto values: 1) Individuals and interactions over processes and tools, 2) Working software over comprehensive documentation, 3) Customer collaboration over contract negotiation, 4) Responding to change over following a plan."},
        {"instruction": "What are the Agile principles?", "input": "", "output": "The 12 Agile principles include: satisfying customers through early delivery, welcoming changing requirements, delivering working software frequently, daily cooperation between business and developers, building projects around motivated individuals, face-to-face conversation, working software as primary progress measure, sustainable development, continuous attention to excellence, simplicity, self-organizing teams, and regular reflection and adjustment."},
        {"instruction": "What is the difference between Agile and Waterfall?", "input": "", "output": "Waterfall is sequential and plan-driven with distinct phases (requirements, design, implementation, testing, deployment). Agile is iterative and incremental, with continuous feedback loops, flexible requirements, and frequent delivery of working software. Waterfall works best for fixed-scope projects; Agile excels when requirements evolve."},
        {"instruction": "What is iterative development?", "input": "", "output": "Iterative development is a software development approach where you build a product in small increments. Each iteration includes planning, analysis, design, implementation, and testing. You deliver a working version after each iteration, allowing for feedback and adjustments before the next cycle."},
        {"instruction": "What is incremental delivery?", "input": "", "output": "Incremental delivery means releasing a product in small, functional pieces rather than all at once. Each increment adds new features or capabilities to the existing product. This allows teams to deliver value early, gather user feedback, and adjust priorities based on real-world usage."},
        {"instruction": "What is continuous improvement in Agile?", "input": "", "output": "Continuous improvement (Kaizen) in Agile means regularly reflecting on processes and making small, incremental changes to become more effective. Teams do this through retrospectives, measuring metrics, experimenting with new practices, and fostering a culture where everyone is empowered to suggest improvements."},
        {"instruction": "What is a minimum viable product (MVP)?", "input": "", "output": "An MVP is the simplest version of a product that delivers core value to users and allows you to test key assumptions with minimal effort. It's not a half-finished product, but a complete solution to a specific problem. The goal is learning: validate ideas quickly before investing in full development."},
        {"instruction": "What is timeboxing?", "input": "", "output": "Timeboxing is setting a fixed time period for an activity. In Agile, sprints are timeboxed (usually 2-4 weeks), as are ceremonies like Daily Standups (15 minutes) and retrospectives. Timeboxing creates urgency, prevents scope creep, and helps teams focus on delivering the most important items within the constraint."},
        {"instruction": "What is the definition of done (DoD)?", "input": "", "output": "The Definition of Done is a shared understanding of what it means for work to be complete. It's a checklist of criteria that must be met before a product increment can be considered releasable. Examples: code reviewed, tests passed, documentation updated, deployed to staging, acceptance criteria met. DoD ensures quality and transparency."},
        {"instruction": "What is the definition of ready (DoR)?", "input": "", "output": "The Definition of Ready is a checklist that a user story must meet before it can be pulled into a sprint. It ensures the team has enough information to start work. Typical criteria: story is clear, acceptance criteria defined, dependencies identified, estimated, small enough to complete in one sprint, and has business value."},
        {"instruction": "What is technical debt?", "input": "", "output": "Technical debt is the implied cost of future rework caused by choosing quick, easy solutions instead of better approaches that take longer. Like financial debt, it accumulates interest - the longer you wait to address it, the more expensive it becomes. Agile teams manage it by allocating time each sprint to refactoring and paying down debt."},
        {"instruction": "What is a spike in Agile?", "input": "", "output": "A spike is a timeboxed research activity used to investigate or prototype a solution before committing to implementation. Teams use spikes when they face high uncertainty, complex technical challenges, or need to evaluate different approaches. The output is knowledge that helps estimate and plan the actual work."},
        {"instruction": "What is refactoring?", "input": "", "output": "Refactoring is the process of restructuring existing code without changing its external behavior. The goal is to improve code quality, readability, maintainability, and performance. In Agile, refactoring is done continuously as part of development, not as a separate phase. It's essential for managing technical debt."},
        {"instruction": "What is pair programming?", "input": "", "output": "Pair programming is an Agile practice where two developers work together at one workstation. One (the driver) writes code while the other (the navigator) reviews each line, thinks strategically, and suggests improvements. They switch roles frequently. Benefits: fewer bugs, knowledge sharing, better design, and faster onboarding."},
        {"instruction": "What is mob programming?", "input": "", "output": "Mob programming is an extension of pair programming where the entire team works together on the same task at the same time. One person types (the driver) while everyone else contributes ideas, reviews, and guides (the navigators). It accelerates learning, improves code quality, and eliminates silos, though it requires strong facilitation."},
        {"instruction": "What is test-driven development (TDD)?", "input": "", "output": "TDD is a development practice where you write automated tests before writing the code. The cycle is: 1) Write a failing test, 2) Write minimal code to pass the test, 3) Refactor the code. Benefits: better design, comprehensive test coverage, living documentation, and confidence to refactor. It forces you to think about requirements and edge cases upfront."},
        {"instruction": "What is behavior-driven development (BDD)?", "input": "", "output": "BDD extends TDD by writing tests in a natural language format (Given-When-Then) that business stakeholders can understand. It focuses on system behavior from the user's perspective. BDD improves communication between developers, testers, and business, ensures tests reflect real requirements, and creates living documentation of system behavior."},
        {"instruction": "What is continuous integration (CI)?", "input": "", "output": "CI is a practice where developers frequently merge code changes into a central repository (multiple times per day). Each merge triggers automated builds and tests to detect integration errors quickly. Benefits: early bug detection, reduced integration problems, faster feedback, and confidence to release. CI is foundational for continuous delivery."},
        {"instruction": "What is continuous delivery (CD)?", "input": "", "output": "Continuous delivery is a software engineering approach where teams produce software in short cycles, ensuring it can be reliably released at any time. Code is always in a deployable state through automated testing, staging environments, and deployment pipelines. CD reduces risk, enables faster feedback, and allows business to decide when to release."},
        {"instruction": "What is continuous deployment?", "input": "", "output": "Continuous deployment goes a step beyond continuous delivery by automatically deploying every change that passes tests to production, without manual approval. This enables multiple deployments per day, rapid feedback loops, and smaller, safer releases. It requires robust automated testing, monitoring, and rollback capabilities."},
        {"instruction": "What is DevOps?", "input": "", "output": "DevOps is a set of practices that combines software development (Dev) and IT operations (Ops) to shorten the development lifecycle and deliver high-quality software continuously. It emphasizes collaboration, automation, continuous integration/delivery, infrastructure as code, and monitoring. DevOps breaks down silos between development and operations teams."},
        {"instruction": "What is a product backlog?", "input": "", "output": "The product backlog is an ordered list of everything that might be needed in the product. It's the single source of requirements, owned by the Product Owner, and continuously refined. Items are prioritized by value, risk, and dependencies. The backlog is never complete - it evolves as the product and understanding of it evolves."},
        {"instruction": "What is a sprint backlog?", "input": "", "output": "The sprint backlog is the set of product backlog items selected for the sprint, plus a plan for delivering them. It's owned by the Development Team and represents their commitment for the sprint. The team updates it daily during the standup. It's a visible, real-time picture of the work the team plans to accomplish."},
        {"instruction": "What is a product increment?", "input": "", "output": "A product increment is the sum of all completed backlog items during a sprint, plus all increments from previous sprints. At the end of each sprint, the increment must be in a usable condition and meet the Definition of Done. It represents concrete progress and is the primary measure of value delivery in Scrum."},
        {"instruction": "What is velocity?", "input": "", "output": "Velocity is the average amount of work (usually in story points) a team completes per sprint. It's calculated by summing the points of fully completed stories. Velocity helps teams forecast future capacity, set realistic sprint goals, and identify process improvements. It's a planning tool, not a performance metric - never compare velocities between teams."},
        {"instruction": "What is a burn-down chart?", "input": "", "output": "A burn-down chart shows the amount of work remaining in a sprint or release over time. The X-axis is time, Y-axis is work (story points or hours). An ideal line shows perfect progress; the actual line shows real progress. If the actual line is above the ideal, you're behind; below means you're ahead. It helps teams track progress and adjust."},
        {"instruction": "What is a burn-up chart?", "input": "", "output": "A burn-up chart shows work completed over time, with two lines: one for total scope and one for completed work. Unlike burn-down, it clearly shows scope changes - if the total scope line moves up, scope was added. Burn-up charts are better for long-term tracking and communicating progress to stakeholders, as they show both progress and scope changes."},
        {"instruction": "What is cumulative flow?", "input": "", "output": "Cumulative flow is a Kanban metric shown as an area chart with bands representing work in different states (To Do, In Progress, Testing, Done). It visualizes workflow, identifies bottlenecks (widening bands), and shows cycle time trends. A healthy cumulative flow diagram has parallel bands of consistent width, indicating smooth, predictable workflow."},
        {"instruction": "What is lead time?", "input": "", "output": "Lead time is the total time from when a request is made until it's delivered to the customer. In Agile, it measures how long a user story takes from creation to deployment. Shorter lead time means faster response to market needs. Teams track lead time to identify delays, improve predictability, and set customer expectations."},
        {"instruction": "What is cycle time?", "input": "", "output": "Cycle time is the time from when work starts on an item until it's completed. Unlike lead time (which includes waiting), cycle time measures actual work duration. In Kanban, it's measured from 'In Progress' to 'Done'. Teams use cycle time to improve efficiency, estimate more accurately, and identify process bottlenecks."},
        {"instruction": "What is throughput?", "input": "", "output": "Throughput is the number of work items completed per unit of time (e.g., stories per week). In Kanban, it's a key metric for measuring team capacity and predicting delivery dates. Teams track throughput to identify trends, set WIP limits, and forecast when backlog items will be completed. Higher throughput with consistent quality indicates process improvement."},
        {"instruction": "What is work in progress (WIP)?", "input": "", "output": "WIP is the number of work items currently in progress but not yet completed. Too much WIP causes context switching, delays, and quality issues. Kanban uses WIP limits to constrain work at each stage, forcing teams to finish before starting new work. This improves flow, reduces cycle time, and increases predictability."},
        {"instruction": "What are WIP limits?", "input": "", "output": "WIP limits are constraints on the maximum number of work items allowed in each workflow stage. They force teams to focus, finish work before starting new tasks, and identify bottlenecks. When a column hits its limit, the team must help clear it before pulling new work. WIP limits improve flow, reduce cycle time, and increase quality."},
        {"instruction": "What is a bottleneck?", "input": "", "output": "A bottleneck is a stage in the workflow where work piles up because capacity is lower than demand. It constrains the entire system's throughput. In Kanban, bottlenecks are visible as wide bands in cumulative flow diagrams or columns hitting WIP limits. To improve flow, you must identify and address bottlenecks - either by increasing capacity there or reducing work arriving at that stage."},
        {"instruction": "What is flow efficiency?", "input": "", "output": "Flow efficiency is the ratio of active work time to total lead time. It measures how much time an item spends being worked on versus waiting. Typical flow efficiency is 15-20% - most time is spent waiting. Improving flow efficiency means reducing wait times, handoffs, and delays. It's a key metric for identifying process waste and improving delivery speed."},
        {"instruction": "What is a value stream?", "input": "", "output": "A value stream is the end-to-end sequence of activities required to deliver value to a customer. It includes all steps from idea to deployment, including wait times and handoffs. Value stream mapping visualizes the flow, identifies waste (non-value-adding activities), and highlights improvement opportunities. Agile teams optimize value streams to deliver faster and with less waste."},
        {"instruction": "What is lean thinking?", "input": "", "output": "Lean thinking focuses on maximizing customer value while minimizing waste. The 5 principles: 1) Identify value from customer's perspective, 2) Map the value stream, 3) Create flow by eliminating interruptions, 4) Establish pull (produce only when needed), 5) Pursue perfection through continuous improvement. Lean eliminates 8 wastes: defects, overproduction, waiting, non-utilized talent, transportation, inventory, motion, and extra-processing."},
        {"instruction": "What are the 8 wastes in Lean?", "input": "", "output": "The 8 wastes (DOWNTIME): 1) Defects - rework and bugs, 2) Overproduction - building more than needed, 3) Waiting - idle time between steps, 4) Non-utilized talent - not using people's skills, 5) Transportation - unnecessary movement of materials, 6) Inventory - excess work in progress, 7) Motion - unnecessary movement of people, 8) Extra-processing - doing more than required."},
    ]
    
    # ===== SCRUM FRAMEWORK (50 examples) =====
    scrum_data = [
        {"instruction": "What is Scrum?", "input": "", "output": "Scrum is a lightweight Agile framework for developing, delivering, and sustaining complex products. It consists of Scrum Teams (Product Owner, Scrum Master, Developers), events (Sprint, Planning, Daily, Review, Retrospective), and artifacts (Backlog, Sprint Backlog, Increment). Scrum uses empirical process control: transparency, inspection, and adaptation."},
        {"instruction": "What are the Scrum roles?", "input": "", "output": "Scrum has 3 accountabilities: 1) Product Owner - maximizes product value, manages the Product Backlog, 2) Scrum Master - ensures Scrum is understood and enacted, removes impediments, coaches the team, 3) Developers - create the increment, self-manage work, ensure quality. Together they form the Scrum Team, typically 10 or fewer people."},
        {"instruction": "What does a Product Owner do?", "input": "", "output": "The Product Owner is accountable for maximizing product value. They: develop and communicate the product goal, create and order Product Backlog items, ensure the backlog is transparent and understood, and make final decisions on requirements. They represent stakeholders and customers, prioritize based on value, and are the single voice of the customer to the team."},
        {"instruction": "What does a Scrum Master do?", "input": "", "output": "The Scrum Master is accountable for establishing Scrum and improving the team's effectiveness. They: coach the team in self-management, facilitate Scrum events, remove impediments, ensure meetings are productive and timeboxed, protect the team from interruptions, and help the organization understand and adopt Scrum. They're a servant-leader, not a project manager."},
        {"instruction": "What do Developers do in Scrum?", "input": "", "output": "Developers (the entire Scrum Team except PO and SM) are accountable for creating the increment. They: plan the Sprint (create Sprint Backlog), ensure quality and Definition of Done, adapt their plan daily toward the Sprint Goal, and hold each other accountable. Developers are self-managing - they decide how to turn backlog items into working software."},
        {"instruction": "What is a Sprint?", "input": "", "output": "A Sprint is a timeboxed event (usually 2-4 weeks) where the team creates a 'Done', useable increment. It's the container for all other Scrum events. Sprints have consistent duration, a Sprint Goal, and end with a review and retrospective. Once a Sprint starts, no changes endanger the Sprint Goal, and quality doesn't decrease. Sprints enable predictability and continuous improvement."},
        {"instruction": "What is Sprint Planning?", "input": "", "output": "Sprint Planning initiates the Sprint by laying out work to be performed. Timeboxed to max 8 hours for a 4-week sprint (shorter for shorter sprints). The team collaborates on: 1) Why - Sprint Goal (what value will be delivered), 2) What - which backlog items will be done, 3) How - the plan for turning items into an increment. The output is the Sprint Backlog."},
        {"instruction": "What is a Daily Standup?", "input": "", "output": "The Daily Scrum is a 15-minute timeboxed event for the Developers to inspect progress toward the Sprint Goal and adapt the Sprint Backlog. Each person answers: What did I do yesterday? What will I do today? Any impediments? It's not a status meeting - it's a planning meeting for the next 24 hours. Same time, same place, every day. The Scrum Master ensures it happens."},
        {"instruction": "What is a Sprint Review?", "input": "", "output": "The Sprint Review inspects the increment and adapts the Product Backlog. Timeboxed to max 4 hours for a 4-week sprint. The team presents completed work to stakeholders, demonstrates the increment, discusses what went well and problems, and collaborates with stakeholders on next steps. It's an informal working session, not a presentation - focused on gathering feedback and adapting the product."},
        {"instruction": "What is a Sprint Retrospective?", "input": "", "output": "The Retrospective is the team's opportunity to inspect itself and create a plan for improvements. Timeboxed to max 3 hours for a 4-week sprint. The team discusses: What went well? What could be improved? What will we commit to improving? The output is actionable improvement items for the next sprint. It's the cornerstone of continuous improvement in Scrum."},
        {"instruction": "What is a Sprint Goal?", "input": "", "output": "A Sprint Goal is the single objective for the Sprint, providing guidance on why the increment is being built. It's created during Sprint Planning and gives the team flexibility in how they achieve it. The goal should be valuable, achievable, and measurable. It helps the team stay focused, make trade-offs, and adapt the plan without losing sight of the purpose."},
        {"instruction": "How do you estimate user stories?", "input": "", "output": "Common estimation techniques: 1) Planning Poker - team members reveal estimates simultaneously using Fibonacci sequence (1,2,3,5,8,13,21), discuss outliers, repeat until consensus, 2) T-Shirt sizing (XS, S, M, L, XL) for relative sizing, 3) Affinity estimation - group similar-sized stories together. Use story points (relative effort), not hours. Estimate as a team, not individuals."},
        {"instruction": "What are story points?", "input": "", "output": "Story points are a relative measure of effort, complexity, and uncertainty - not time. A 2-point story isn't twice as fast as a 1-point story; it's roughly twice as complex or effort-intensive. Teams use Fibonacci numbers (1,2,3,5,8,13) because they reflect uncertainty - bigger stories have more unknowns. Story points help teams forecast based on velocity, not individual productivity."},
        {"instruction": "What is planning poker?", "input": "", "output": "Planning Poker is a consensus-based estimation technique. Each estimator has cards with Fibonacci numbers. The Product Owner presents a story, the team discusses, then everyone simultaneously reveals their estimate. If estimates differ widely, the high and low estimators explain their reasoning, and the team re-estimates. This continues until estimates converge. It prevents anchoring bias and ensures everyone's voice is heard."},
        {"instruction": "What is the INVEST criteria?", "input": "", "output": "INVEST is a checklist for good user stories: Independent (can be developed separately), Negotiable (not a fixed contract), Valuable (delivers value to users/customers), Estimable (team can size it), Small (fits in one sprint), Testable (has clear acceptance criteria). If a story fails INVEST, split or refine it before bringing it into a sprint."},
        {"instruction": "How do you split a user story?", "input": "", "output": "Split stories using these strategies: 1) By workflow steps (each step becomes a story), 2) By business rule variations (different rules = different stories), 3) By type of user (admin vs regular user), 4) By CRUD operations (create, read, update, delete separately), 5) By happy path vs edge cases, 6) By platform (web, mobile, API). Keep each piece valuable and testable."},
        {"instruction": "What is backlog refinement?", "input": "", "output": "Backlog refinement (formerly grooming) is the ongoing process of adding detail, estimates, and order to product backlog items. It's not a formal Scrum event but typically takes 5-10% of team capacity. Activities: breaking down large stories, adding acceptance criteria, estimating, reordering, removing obsolete items. The goal is to keep the backlog healthy and ready for sprint planning."},
        {"instruction": "What is a user story?", "input": "", "output": "A user story is a short, simple description of a feature from the user's perspective. Format: 'As a [type of user], I want [some goal], so that [some reason]'. It's a placeholder for conversation, not a detailed specification. Good stories follow INVEST criteria and include acceptance criteria. Stories focus on user value, not technical implementation."},
        {"instruction": "What are acceptance criteria?", "input": "", "output": "Acceptance criteria define the conditions a user story must meet to be considered complete. They're specific, testable, and written from the user's perspective. Format: 'Given [context], when [action], then [result]'. They clarify requirements, guide development, form the basis for tests, and prevent scope creep. Each story should have multiple acceptance criteria covering happy paths and edge cases."},
        {"instruction": "What is a task in Scrum?", "input": "", "output": "A task is a unit of work needed to complete a user story, typically estimated in hours (not story points). Tasks are identified during sprint planning and make up the Sprint Backlog. They're technical activities like 'design database schema', 'implement API', 'write unit tests'. Tasks are owned by individual developers, unlike stories which are owned by the team. Tasks should be small enough to complete in a day."},
        {"instruction": "What is the sprint backlog?", "input": "", "output": "The Sprint Backlog is the set of Product Backlog items selected for the sprint, plus a plan for delivering the increment. It's owned by the Developers and updated daily. It's a visible, real-time picture of the team's work. Unlike the Product Backlog, it's detailed enough to track daily progress. The team modifies it during the sprint as they learn more."},
        {"instruction": "What is the product backlog?", "input": "", "output": "The Product Backlog is an ordered list of everything needed in the product. It's owned by the Product Owner and is never 'complete'. Items are ordered by value, risk, dependencies, and timing. It's dynamic - constantly updated as the product evolves. The top items are refined and ready; lower items are vague. It's the single source of work for the Scrum Team."},
        {"instruction": "What is a burndown chart used for?", "input": "", "output": "A burndown chart tracks remaining work in a sprint or release. The ideal line shows perfect progress; the actual line shows real progress. If actual is above ideal, the team is behind schedule. If below, they're ahead. Teams use it to: identify when they'll complete the sprint goal, spot trends early, adjust scope or process if needed, and communicate progress to stakeholders."},
        {"instruction": "What is a sprint review?", "input": "", "output": "The Sprint Review is where the team inspects the increment and adapts the Product Backlog. Attendees include the Scrum Team and key stakeholders. The team demonstrates completed work, discusses what went well and problems encountered, and collaborates on next steps. It's a working session, not a presentation - focused on feedback, not approval. Output: revised Product Backlog for the next sprint."},
        {"instruction": "What is a retrospective?", "input": "", "output": "The Sprint Retrospective is the team's opportunity to inspect itself and plan improvements. The team discusses: What went well during the sprint? What problems were encountered? How were those problems solved? What will we do differently next sprint? The output is 1-3 concrete, actionable improvement items for the next sprint. It's the most important event for continuous improvement."},
        {"instruction": "What are common retrospective formats?", "input": "", "output": "Popular formats: 1) Start-Stop-Continue (what to start doing, stop doing, continue doing), 2) 4 Ls (Liked, Learned, Lacked, Longed for), 3) Sailboat (what anchors us, what pushes us forward, risks ahead, the goal), 4) Mad-Sad-Glad (emotions during the sprint), 5) Timeline (chronological review of the sprint). Vary formats to keep retrospectives engaging and uncover different insights."},
        {"instruction": "How do you handle scope creep in a sprint?", "input": "", "output": "Scope creep during a sprint should be minimized. If new work is absolutely necessary: 1) The Product Owner and team discuss the impact, 2) If it endangers the Sprint Goal, negotiate removing equivalent work, 3) Add new items to the Product Backlog (not Sprint Backlog) for future sprints, 4) Only add to current sprint if it's critical and the team agrees. Protect the Sprint Goal!"},
        {"instruction": "What if the team can't finish the sprint?", "input": "", "output": "If the team realizes they can't complete the Sprint Goal: 1) The team discusses options early (not at sprint end), 2) The Product Owner may descope low-priority items, 3) The team focuses on completing the highest-value items, 4) Unfinished items return to the Product Backlog for re-estimation and reprioritization. Don't extend the sprint - instead, learn from it in the retrospective."},
        {"instruction": "What if the sprint goal becomes obsolete?", "input": "", "output": "If the Sprint Goal becomes obsolete (e.g., market change, technical impossibility), only the Product Owner can cancel the sprint. This is rare and drastic. When cancelled: completed items are reviewed, potentially releasable items are accepted, incomplete items are re-estimated and returned to the Product Backlog. A new sprint planning starts immediately. The goal should rarely change mid-sprint."},
        {"instruction": "What is a self-organizing team?", "input": "", "output": "A self-organizing team chooses how best to accomplish their work, rather than being directed by others outside the team. They decide who does what, when, and how. This leads to increased creativity, ownership, and commitment. Self-organization doesn't mean no structure - it means the team internally manages their processes. The Scrum Master helps the team become more self-organizing over time."},
        {"instruction": "What is a cross-functional team?", "input": "", "output": "A cross-functional team has all the skills needed to create value each sprint - no dependencies on people outside the team. This doesn't mean everyone has all skills; it means the team collectively has the right mix: development, testing, UX, DevOps, etc. Cross-functional teams reduce handoffs, improve collaboration, and deliver faster. They're 'T-shaped' - deep expertise plus broad understanding."},
        {"instruction": "What is the ideal Scrum team size?", "input": "", "output": "The Scrum Guide recommends 10 or fewer people total (1 Product Owner, 1 Scrum Master, 3-9 Developers). Smaller teams may not have enough skills; larger teams have too much communication overhead. The ideal size depends on the product complexity, but 5-9 developers is common. If the team grows beyond 10, consider splitting into multiple coordinated Scrum Teams working on the same product."},
        {"instruction": "What is the timebox for Scrum events?", "input": "", "output": "Sprint: 1 month max (usually 2-4 weeks, consistent). Sprint Planning: 8 hours for 4-week sprint (proportional for shorter sprints). Daily Scrum: 15 minutes. Sprint Review: 4 hours for 4-week sprint. Sprint Retrospective: 3 hours for 4-week sprint. Timeboxes create focus and efficiency. If meetings consistently exceed timeboxes, the team should improve their facilitation and preparation."},
        {"instruction": "What is the role of the Product Owner?", "input": "", "output": "The Product Owner is accountable for maximizing product value. They: develop and communicate the Product Goal, create and order Product Backlog items, ensure the backlog is transparent and understood, and make final decisions on requirements. They represent stakeholders and customers, prioritize based on value, and are the single voice of the customer. They don't dictate solutions - they define the 'what' and 'why'."},
        {"instruction": "What is the role of the Scrum Master?", "input": "", "output": "The Scrum Master is accountable for establishing Scrum and improving team effectiveness. They: coach the team in self-management and cross-functionality, facilitate Scrum events, remove impediments, ensure meetings are productive and timeboxed, protect the team from interruptions, and help the organization adopt Scrum. They're a servant-leader who enables the team, not a manager who directs them."},
        {"instruction": "What is the role of Developers?", "input": "", "output": "Developers (everyone except PO and SM) are accountable for creating the increment. They: plan the Sprint by creating the Sprint Backlog, ensure quality and adherence to Definition of Done, adapt their plan daily toward the Sprint Goal, and hold each other accountable. They're self-managing - they decide how to turn backlog items into working software. 'Developers' includes all roles doing the work."},
        {"instruction": "What is empirical process control?", "input": "", "output": "Empirical process control is the foundation of Scrum. It's based on three pillars: 1) Transparency - significant aspects of the process must be visible to those responsible for the outcome, 2) Inspection - Scrum artifacts and progress must be frequently inspected to detect problems, 3) Adaptation - if aspects deviate outside acceptable limits, adjustments must be made quickly. Scrum uses empiricism to handle complexity."},
        {"instruction": "What are the Scrum values?", "input": "", "output": "The 5 Scrum values are: 1) Commitment - to achieving the Sprint Goal and supporting the team, 2) Courage - to do the right thing and work on tough problems, 3) Focus - on the Sprint Goal and work of the Sprint, 4) Openness - about all work and challenges, 5) Respect - for each other as capable, independent people. Living these values enables the transparency, inspection, and adaptation that Scrum requires."},
        {"instruction": "What is the Definition of Done?", "input": "", "output": "The Definition of Done is a formal description of the state of the Increment when it meets the quality measures required for the product. It creates transparency and shared understanding. If a Product Backlog item doesn't meet the DoD, it can't be released or presented at the Sprint Review. The entire Scrum Team must adhere to it. Examples: code reviewed, tests passed, documentation updated, deployed to staging."},
        {"instruction": "What is a product increment?", "input": "", "output": "An Increment is a concrete stepping stone toward the Product Goal. Each Increment is additive to all prior Increments and thoroughly verified, ensuring all Increments work together. At the end of a Sprint, the new Increment must be 'Done', usable, and meet the Definition of Done. Multiple Increments may be created within a Sprint. The sum of all Increments is the product."},
        {"instruction": "What is technical debt in Scrum?", "input": "", "output": "Technical debt is the cost of future rework caused by choosing quick solutions over better approaches. In Scrum, it's managed by: including refactoring in the Definition of Done, allocating time each sprint to address debt, making debt visible in the Product Backlog, and discussing it in retrospectives. Ignoring debt slows future sprints; managing it maintains sustainable pace and quality."},
        {"instruction": "What is a spike in Scrum?", "input": "", "output": "A spike is a timeboxed research activity to reduce uncertainty before committing to implementation. Teams use spikes when facing high complexity, unknown technology, or unclear requirements. The output is knowledge that helps estimate and plan the actual work. Spikes are Product Backlog items, estimated in story points, and have their own Definition of Done (usually 'research complete, findings documented')."},
        {"instruction": "What is refactoring in Scrum?", "input": "", "output": "Refactoring is improving code structure without changing external behavior. In Scrum, it's part of the Definition of Done - code must be clean and maintainable. Teams refactor continuously during development, not as a separate phase. If significant refactoring is needed, it can be a Product Backlog item. Refactoring reduces technical debt, improves velocity over time, and maintains code quality."},
        {"instruction": "What is pair programming in Scrum?", "input": "", "output": "Pair programming is an Agile practice where two developers work together at one workstation. One (driver) writes code while the other (navigator) reviews and guides. They switch frequently. Benefits: fewer defects, knowledge sharing, better design, faster onboarding. It's not required in Scrum but is a valuable practice teams can adopt. It's especially useful for complex tasks and mentoring."},
        {"instruction": "What is mob programming in Scrum?", "input": "", "output": "Mob programming extends pair programming to the entire team working together on one task. One person types (driver) while everyone contributes ideas (navigators). Benefits: accelerated learning, eliminated silos, higher quality, shared ownership. Challenges: requires strong facilitation, can be exhausting. Teams use it for complex problems, knowledge transfer, or when starting new projects. It's optional but powerful."},
        {"instruction": "What is test-driven development in Scrum?", "input": "", "output": "TDD is writing automated tests before code. The cycle: 1) Write a failing test, 2) Write minimal code to pass, 3) Refactor. In Scrum, TDD supports the Definition of Done by ensuring testability and quality. Benefits: better design, comprehensive test coverage, living documentation, confidence to refactor. TDD is a practice teams can adopt; it's not required by Scrum but aligns with its values of quality and transparency."},
        {"instruction": "What is continuous integration in Scrum?", "input": "", "output": "CI is merging code frequently (multiple times per day) and running automated builds/tests. In Scrum, CI supports the Definition of Done by catching integration issues early. Benefits: early bug detection, reduced integration problems, faster feedback, confidence to release. CI is foundational for continuous delivery. Teams should aim to integrate daily, with automated tests running on every commit."},
        {"instruction": "What is continuous delivery in Scrum?", "input": "", "output": "CD is keeping code in a deployable state at all times through automated testing and deployment pipelines. In Scrum, each Increment should be potentially shippable. CD enables this by automating builds, tests, and deployments. Benefits: reduced risk, faster feedback, ability to release anytime. The Product Owner decides when to release to users; the team ensures it's always possible."},
        {"instruction": "What is a Scrum of Scrums?", "input": "", "output": "A Scrum of Scrums (or MetaScrum) coordinates multiple Scrum Teams working on the same product. Representatives from each team meet regularly (often daily) to discuss: progress toward the overall product goal, dependencies between teams, impediments that need escalation, and integration issues. It's not a status meeting - it's for coordination. The Product Owner and Scrum Masters typically facilitate."},
        {"instruction": "What is SAFe (Scaled Agile Framework)?", "input": "", "output": "SAFe is a framework for scaling Agile across large organizations. It provides structured guidance for roles, responsibilities, and artifacts at team, program, and portfolio levels. SAFe uses Agile Release Trains (ARTs) - teams of 50-125 people working together. It includes events like PI Planning (quarterly), System Demos, and Inspect & Adapt. SAFe is controversial - some love its structure, others find it too heavy."},
    ]
    
    # ===== KANBAN (30 examples) =====
    kanban_data = [
        {"instruction": "What is Kanban?", "input": "", "output": "Kanban is a visual workflow management method that helps teams visualize work, limit work-in-progress, and maximize flow. It starts with your current process and evolves through incremental changes. Kanban uses a board with columns representing workflow stages, cards representing work items, and WIP limits for each column. It's less prescriptive than Scrum - you keep your existing roles and cadence."},
        {"instruction": "What are the Kanban practices?", "input": "", "output": "The 6 Kanban practices: 1) Visualize the workflow (board with columns), 2) Limit WIP (set max items per column), 3) Manage flow (optimize movement through the system), 4) Make process policies explicit (clear rules for each stage), 5) Implement feedback loops (regular meetings), 6) Improve collaboratively (use metrics and experiments). These practices help teams deliver faster with higher quality."},
        {"instruction": "What is a Kanban board?", "input": "", "output": "A Kanban board visualizes the workflow with columns representing stages (e.g., To Do, In Progress, Testing, Done) and cards representing work items. It makes work visible, shows bottlenecks, and helps manage flow. Boards can be physical (sticky notes on a wall) or digital (Jira, Trello, Azure DevOps). The key is that everyone can see the current state of all work at a glance."},
        {"instruction": "What are WIP limits in Kanban?", "input": "", "output": "WIP limits constrain the maximum number of work items allowed in each workflow stage. They force teams to finish work before starting new tasks, reducing multitasking and context switching. When a column hits its limit, the team must help clear it before pulling new work. WIP limits expose bottlenecks, improve flow, reduce cycle time, and increase predictability. Start with generous limits and tighten over time."},
        {"instruction": "What is flow in Kanban?", "input": "", "output": "Flow is the movement of work items through the system from start to finish. Good flow means items move smoothly and predictably; poor flow means items get stuck, wait, or cycle back. Kanban optimizes flow by: visualizing work, limiting WIP, identifying bottlenecks, reducing batch sizes, and improving collaboration. Metrics like cycle time and throughput measure flow. The goal is smooth, predictable delivery."},
        {"instruction": "What is cycle time in Kanban?", "input": "", "output": "Cycle time is the time from when work starts on an item until it's completed. In Kanban, it's measured from 'In Progress' to 'Done'. Teams track cycle time to: improve efficiency, estimate more accurately, identify process bottlenecks, and set customer expectations. Shorter cycle time means faster delivery. Teams aim to reduce cycle time through WIP limits, bottleneck resolution, and process improvements."},
        {"instruction": "What is lead time in Kanban?", "input": "", "output": "Lead time is the total time from when a request is made until it's delivered. It includes waiting time before work starts, plus cycle time. Lead time measures the customer's perspective - how long they wait for value. Teams track lead time to: improve responsiveness, set delivery expectations, and identify delays in the intake process. Shorter lead time means faster response to market needs."},
        {"instruction": "What is throughput in Kanban?", "input": "", "output": "Throughput is the number of work items completed per unit of time (e.g., stories per week). It measures team capacity and predicts delivery dates. Teams track throughput to: identify trends, set WIP limits, and forecast when backlog items will be completed. Higher throughput with consistent quality indicates process improvement. Throughput is more stable than velocity and works well for forecasting."},
        {"instruction": "What is a cumulative flow diagram?", "input": "", "output": "A cumulative flow diagram (CFD) is an area chart showing work in different states over time. Each band represents a workflow stage. A healthy CFD has parallel bands of consistent width, indicating smooth flow. Widening bands show bottlenecks; narrowing bands show underutilization. CFDs visualize flow, identify problems, and show cycle time trends. They're the primary metric for Kanban teams."},
        {"instruction": "What is a bottleneck in Kanban?", "input": "", "output": "A bottleneck is a workflow stage where work piles up because capacity is lower than demand. It constrains the entire system's throughput. In Kanban, bottlenecks are visible as: wide bands in CFDs, columns hitting WIP limits, or long queues before a stage. To improve flow, you must identify and address bottlenecks - either by increasing capacity there or reducing work arriving at that stage."},
        {"instruction": "What is the difference between Scrum and Kanban?", "input": "", "output": "Scrum: timeboxed sprints (2-4 weeks), fixed roles (PO, SM, Devs), prescribed events, velocity-based planning, batch delivery. Kanban: continuous flow, no required roles or events, WIP limits, cycle time-based planning, continuous delivery. Scrum is prescriptive with a reset every sprint; Kanban is evolutionary, starting with your current process. Many teams use a hybrid (Scrumban) combining the best of both."},
        {"instruction": "What is Scrumban?", "input": "", "output": "Scrumban is a hybrid of Scrum and Kanban. Teams keep Scrum's structure (roles, events, sprints) but adopt Kanban's practices (visualization, WIP limits, flow metrics). Common patterns: use a Kanban board within sprints, limit WIP to improve flow, use cycle time for estimation, and release continuously rather than at sprint end. Scrumban is popular for teams transitioning from Scrum or needing more flexibility."},
        {"instruction": "What are Kanban cadences?", "input": "", "output": "Kanban cadences are regular rhythms for different activities: 1) Replenishment (weekly) - prioritize and pull new work, 2) Delivery (daily or continuous) - release completed work, 3) Service Delivery Review (bi-weekly) - review flow and service levels, 4) Operations Review (monthly) - coordinate across teams, 5) Risk Review (monthly) - assess risks, 6) Strategy Review (quarterly) - align with business goals."},
        {"instruction": "What is a Kanban replenishment meeting?", "input": "", "output": "The replenishment meeting (similar to sprint planning) is where the team prioritizes and pulls new work into the system. It's held regularly (often weekly) and focuses on: reviewing the backlog, prioritizing based on customer needs, pulling items into the 'To Do' column, and ensuring the team has enough work. Unlike sprint planning, there's no sprint commitment - work is pulled as capacity allows."},
        {"instruction": "What is a service delivery review in Kanban?", "input": "", "output": "The service delivery review is a regular meeting (often bi-weekly) where the team reviews flow metrics, service level agreements, and customer satisfaction. They discuss: cycle time trends, throughput, bottlenecks, blocked items, and process improvements. The goal is to ensure the team is delivering value effectively and meeting customer expectations. It's a feedback loop for continuous improvement."},
        {"instruction": "What are classes of service in Kanban?", "input": "", "output": "Classes of service categorize work items by urgency and handling policies. Common classes: 1) Expedite (drop everything, fix now), 2) Fixed Date (must be done by a specific date), 3) Standard (normal priority), 4) Intangible (low urgency, high long-term value). Each class has different WIP limits, policies, and service level expectations. Classes help teams prioritize and manage different types of work appropriately."},
        {"instruction": "What is a pull system in Kanban?", "input": "", "output": "A pull system means work is pulled into the next stage only when there's capacity, rather than being pushed based on a schedule. In Kanban, when a column has capacity (below WIP limit), the team pulls the next highest-priority item from the previous column. Pull systems reduce overproduction, expose bottlenecks, and improve flow. They're the opposite of push systems, which create queues and delays."},
        {"instruction": "What is Little's Law in Kanban?", "input": "", "output": "Little's Law states: Average Cycle Time = Average WIP / Average Throughput. It's a fundamental relationship in flow systems. In Kanban, it means: if you reduce WIP (numerator) while maintaining throughput (denominator), cycle time decreases. Or: if you increase throughput while keeping WIP constant, cycle time decreases. Little's Law helps teams predict cycle time and understand the impact of WIP limits."},
        {"instruction": "What is flow efficiency in Kanban?", "input": "", "output": "Flow efficiency is the ratio of active work time to total lead time. It measures how much time an item spends being worked on versus waiting. Typical flow efficiency is 15-20% - most time is spent waiting in queues. Improving flow efficiency means reducing wait times, handoffs, and delays. It's a key metric for identifying process waste and improving delivery speed. Kanban teams aim to increase flow efficiency over time."},
        {"instruction": "What is a Kanban board?", "input": "", "output": "A Kanban board visualizes the workflow with columns representing stages and cards representing work items. Columns typically include: Backlog, To Do, In Progress, Testing, Done. Cards move from left to right as work progresses. WIP limits are set for each column. The board makes work visible, shows bottlenecks, and helps manage flow. It can be physical (wall with sticky notes) or digital (Jira, Trello)."},
        {"instruction": "What are explicit policies in Kanban?", "input": "", "output": "Explicit policies are clear, visible rules for how work moves through the system. They answer: When can an item move to the next stage? What's the Definition of Done for each stage? Who can pull work? What happens when WIP limits are hit? Policies should be simple, visible, and evolved through experimentation. They reduce ambiguity, improve consistency, and make the process transparent to everyone."},
        {"instruction": "What is a Kanban cadence?", "input": "", "output": "Kanban cadences are regular rhythms for different activities: replenishment (pulling new work), delivery (releasing completed work), and reviews (inspecting flow and improving). Unlike Scrum's fixed sprint cadence, Kanban cadences can vary by activity. Common cadences: daily standups, weekly replenishment, bi-weekly service delivery reviews, monthly operations reviews. Cadences create predictability and feedback loops."},
        {"instruction": "What is a Kanban replenishment meeting?", "input": "", "output": "The replenishment meeting is where the team prioritizes and pulls new work into the system. It's held regularly (often weekly) and focuses on: reviewing the backlog, prioritizing based on customer needs, pulling items into the 'To Do' column, and ensuring the team has enough work. Unlike sprint planning, there's no sprint commitment - work is pulled as capacity allows. The goal is to keep the pipeline full without overloading."},
        {"instruction": "What is a Kanban service delivery review?", "input": "", "output": "The service delivery review is a regular meeting (often bi-weekly) where the team reviews flow metrics, service level agreements, and customer satisfaction. They discuss: cycle time trends, throughput, bottlenecks, blocked items, and process improvements. The goal is to ensure the team is delivering value effectively and meeting customer expectations. It's a feedback loop for continuous improvement, similar to a sprint review but focused on flow."},
        {"instruction": "What are Kanban classes of service?", "input": "", "output": "Classes of service categorize work items by urgency and handling policies. Common classes: Expedite (drop everything, fix now), Fixed Date (must be done by a specific date), Standard (normal priority), Intangible (low urgency, high long-term value). Each class has different WIP limits, policies, and service level expectations. Classes help teams prioritize and manage different types of work appropriately, ensuring urgent items get attention without derailing everything."},
        {"instruction": "What is a Kanban pull system?", "input": "", "output": "A pull system means work is pulled into the next stage only when there's capacity, rather than being pushed based on a schedule. In Kanban, when a column has capacity (below WIP limit), the team pulls the next highest-priority item from the previous column. Pull systems reduce overproduction, expose bottlenecks, and improve flow. They're the opposite of push systems, which create queues and delays. Pull is core to Kanban."},
        {"instruction": "What is Little's Law in Kanban?", "input": "", "output": "Little's Law states: Average Cycle Time = Average WIP / Average Throughput. It's a fundamental relationship in flow systems. In Kanban, it means: if you reduce WIP while maintaining throughput, cycle time decreases. Or: if you increase throughput while keeping WIP constant, cycle time decreases. Little's Law helps teams predict cycle time, understand the impact of WIP limits, and optimize their system for faster delivery."},
        {"instruction": "What is flow efficiency in Kanban?", "input": "", "output": "Flow efficiency is the ratio of active work time to total lead time. It measures how much time an item spends being worked on versus waiting. Typical flow efficiency is 15-20% - most time is spent waiting in queues. Improving flow efficiency means reducing wait times, handoffs, and delays. It's a key metric for identifying process waste and improving delivery speed. Kanban teams aim to increase flow efficiency over time."},
        {"instruction": "What is a Kanban board?", "input": "", "output": "A Kanban board visualizes the workflow with columns representing stages and cards representing work items. Columns typically include: Backlog, To Do, In Progress, Testing, Done. Cards move from left to right as work progresses. WIP limits are set for each column. The board makes work visible, shows bottlenecks, and helps manage flow. It can be physical (wall with sticky notes) or digital (Jira, Trello, Azure DevOps)."},
        {"instruction": "What are explicit policies in Kanban?", "input": "", "output": "Explicit policies are clear, visible rules for how work moves through the system. They answer: When can an item move to the next stage? What's the Definition of Done for each stage? Who can pull work? What happens when WIP limits are hit? Policies should be simple, visible, and evolved through experimentation. They reduce ambiguity, improve consistency, and make the process transparent to everyone."},
    ]
    
    # ===== ESTIMATION & PLANNING (30 examples) =====
    estimation_data = [
        {"instruction": "How do you estimate user stories?", "input": "", "output": "Common estimation techniques: 1) Planning Poker - team reveals estimates simultaneously using Fibonacci (1,2,3,5,8,13,21), discuss outliers, repeat until consensus, 2) T-Shirt sizing (XS, S, M, L, XL) for relative sizing, 3) Affinity estimation - group similar-sized stories together. Use story points (relative effort), not hours. Estimate as a team, not individuals. The goal is shared understanding, not perfect accuracy."},
        {"instruction": "What are story points?", "input": "", "output": "Story points are a relative measure of effort, complexity, and uncertainty - not time. A 2-point story isn't twice as fast as a 1-point story; it's roughly twice as complex or effort-intensive. Teams use Fibonacci numbers (1,2,3,5,8,13) because they reflect uncertainty - bigger stories have more unknowns. Story points help teams forecast based on velocity, not individual productivity. They're abstract, allowing teams to define their own scale."},
        {"instruction": "What is planning poker?", "input": "", "output": "Planning Poker is a consensus-based estimation technique. Each estimator has cards with Fibonacci numbers. The Product Owner presents a story, the team discusses, then everyone simultaneously reveals their estimate. If estimates differ widely, the high and low estimators explain their reasoning, and the team re-estimates. This continues until estimates converge. It prevents anchoring bias and ensures everyone's voice is heard."},
        {"instruction": "What is the bucket system for estimation?", "input": "", "output": "The bucket system is a fast estimation technique for large backlogs. Create columns labeled with Fibonacci numbers (1,2,3,5,8,13,20,40,100). Place a few 'reference stories' in appropriate columns. Then, team members rapidly place remaining stories in buckets by comparing them to references. Discuss outliers and adjust. It's much faster than planning poker for large backlogs, though less precise. Good for initial prioritization."},
        {"instruction": "What is affinity estimation?", "input": "", "output": "Affinity estimation is a silent, visual technique for sizing many stories quickly. Team members place stories on a wall in relative size order (smallest to largest) without discussion. Once placed, the team reviews and adjusts. Then, assign Fibonacci numbers to columns. It's fast, collaborative, and builds shared understanding. Affinity estimation works well for large backlogs and diverse teams. It's less precise but faster than planning poker."},
        {"instruction": "What is T-Shirt sizing?", "input": "", "output": "T-Shirt sizing uses sizes (XS, S, M, L, XL, XXL) instead of story points for estimation. It's intuitive and works well for high-level planning or non-technical stakeholders. Teams can map sizes to story points later (e.g., S=2, M=5, L=8, XL=13). T-Shirt sizing is less precise but easier to understand. It's useful for roadmap planning, portfolio prioritization, and communicating with business stakeholders who don't understand story points."},
        {"instruction": "How do you calculate velocity?", "input": "", "output": "Velocity is the average story points completed per sprint. Calculate it by: 1) Sum the points of fully completed stories (meeting Definition of Done) for each sprint, 2) Average the last 3-6 sprints, 3) Use this average for future sprint planning. Don't include partially done stories. Velocity fluctuates - that's normal. Use it for planning, not performance measurement. Never compare velocities between teams."},
        {"instruction": "What is ideal days estimation?", "input": "", "output": "Ideal days estimate how long a story would take if there were no interruptions, meetings, or delays. It's different from elapsed days (actual calendar time). A 2 ideal-day story might take 4 elapsed days due to meetings, context switching, and dependencies. Ideal days help teams understand complexity, but they're harder to calibrate than story points. Most teams prefer story points because they're relative and team-specific."},
        {"instruction": "What is the three-point estimation technique?", "input": "", "output": "Three-point estimation uses three values: Optimistic (O), Most Likely (M), and Pessimistic (P). The expected value is calculated as: (O + 4M + P) / 6. This accounts for uncertainty and risk. For example: O=2 days, M=5 days, P=10 days → Expected = (2 + 20 + 10) / 6 = 5.3 days. Three-point estimation is more accurate than single-point estimates and helps teams understand the range of possible outcomes."},
        {"instruction": "What is function point analysis?", "input": "", "output": "Function Point Analysis (FPA) measures software size based on user functionality. It counts: external inputs, outputs, inquiries, files, and interfaces. Each is weighted by complexity (low, medium, high). The total function points estimate effort using industry standards. FPA is objective and technology-independent, but it's complex and requires training. It's used more in traditional projects than Agile, though some organizations use it for benchmarking."},
        {"instruction": "What is story mapping?", "input": "", "output": "Story mapping is a visual technique for organizing user stories along two dimensions: user activities (horizontal axis) and priority (vertical axis). It creates a 'map' of the product from the user's perspective. The horizontal axis shows the user journey; the vertical axis shows priority (most important at top). Story maps help teams: understand the big picture, prioritize releases, identify gaps, and plan MVPs. They're collaborative and visual."},
        {"instruction": "What is impact mapping?", "input": "", "output": "Impact mapping is a strategic planning technique that connects goals to deliverables. It asks: Why? (goal), Who? (actors), How? (impacts), What? (deliverables). The map visualizes the path from business goals to features. It helps teams: focus on outcomes over outputs, identify assumptions, prioritize high-impact work, and avoid building unnecessary features. Impact maps are created collaboratively and revised as learning occurs."},
        {"instruction": "What is roadmap planning?", "input": "", "output": "Roadmap planning creates a high-level timeline of major releases and milestones. It's not a detailed project plan - it's a strategic communication tool. Roadmaps show: themes (not specific features), timeframes (quarters, not dates), goals and outcomes, and dependencies. They're owned by the Product Owner and shared with stakeholders. Roadmaps should be living documents, updated as priorities change. They balance flexibility with predictability."},
        {"instruction": "What is release planning?", "input": "", "output": "Release planning defines what will be delivered in a release and when. It considers: product vision, roadmap, backlog priorities, team velocity, and dependencies. The output is a plan showing which sprints will deliver which features, and when the release will occur. Release plans are estimates, not commitments - they're revised as the team learns. They help stakeholders understand timing and help the team coordinate work across sprints."},
        {"instruction": "What is sprint capacity planning?", "input": "", "output": "Sprint capacity planning estimates how much work the team can commit to in a sprint. It considers: team velocity (historical average), team availability (vacations, holidays), and known interruptions (meetings, support). Capacity is usually less than velocity to account for variability. Teams use capacity to select backlog items for sprint planning. It's a collaborative discussion, not a mathematical formula. Overcommitting leads to burnout and failed sprints."},
        {"instruction": "What is the cone of uncertainty?", "input": "", "output": "The cone of uncertainty shows how estimate accuracy improves as a project progresses. At the start, estimates can be off by 4x (0.25x to 4x). As requirements clarify and work is completed, the range narrows. By the end, estimates are accurate within 1.25x. The cone teaches: don't commit to long-term dates early, expect estimates to change, and re-estimate regularly. Agile embraces uncertainty through iteration and adaptation."},
        {"instruction": "What is Monte Carlo simulation?", "input": "", "output": "Monte Carlo simulation uses historical data to forecast future outcomes probabilistically. For Agile, it simulates thousands of possible sprint outcomes based on historical throughput. The output is a probability distribution: 'There's an 85% chance we'll complete 40-50 stories by Q3'. Monte Carlo is more realistic than single-point estimates because it accounts for variability. Tools like ActionableAgree and Jira use it for forecasting."},
        {"instruction": "What is throughput-based forecasting?", "input": "", "output": "Throughput-based forecasting uses historical throughput (items completed per week) to predict when backlog items will be done. It's simpler than velocity-based forecasting because it uses item count, not story points. Teams calculate average throughput and standard deviation, then use Monte Carlo simulation to generate probabilistic forecasts. Throughput-based forecasting is more stable than velocity and works well for Kanban teams."},
        {"instruction": "What is velocity-based forecasting?", "input": "", "output": "Velocity-based forecasting uses historical velocity (story points per sprint) to predict when backlog items will be completed. Teams average the last 3-6 sprints, then divide remaining backlog points by average velocity to estimate sprints needed. This is a rough estimate - use Monte Carlo simulation for probabilistic forecasts. Velocity-based forecasting works for Scrum teams but is less stable than throughput-based forecasting."},
        {"instruction": "What is a sprint goal?", "input": "", "output": "A Sprint Goal is the single objective for the Sprint, providing guidance on why the increment is being built. It's created during Sprint Planning and gives the team flexibility in how they achieve it. The goal should be valuable, achievable, and measurable. It helps the team stay focused, make trade-offs, and adapt the plan without losing sight of the purpose. If the goal becomes obsolete, the Product Owner can cancel the sprint."},
        {"instruction": "What is a sprint backlog?", "input": "", "output": "The Sprint Backlog is the set of Product Backlog items selected for the sprint, plus a plan for delivering the increment. It's owned by the Developers and updated daily. It's a visible, real-time picture of the team's work. Unlike the Product Backlog, it's detailed enough to track daily progress. The team modifies it during the sprint as they learn more. It's their commitment for the sprint."},
        {"instruction": "What is a product backlog?", "input": "", "output": "The Product Backlog is an ordered list of everything needed in the product. It's owned by the Product Owner and is never 'complete'. Items are ordered by value, risk, dependencies, and timing. It's dynamic - constantly updated as the product evolves. The top items are refined and ready; lower items are vague. It's the single source of work for the Scrum Team. The backlog is refined continuously in backlog refinement sessions."},
        {"instruction": "What is backlog refinement?", "input": "", "output": "Backlog refinement is the ongoing process of adding detail, estimates, and order to product backlog items. It's not a formal Scrum event but typically takes 5-10% of team capacity. Activities: breaking down large stories, adding acceptance criteria, estimating, reordering, removing obsolete items. The goal is to keep the backlog healthy and ready for sprint planning. Well-refined items meet the Definition of Ready and can be pulled into a sprint."},
        {"instruction": "What is the Definition of Ready?", "input": "", "output": "The Definition of Ready is a checklist that a user story must meet before it can be pulled into a sprint. It ensures the team has enough information to start work. Typical criteria: story is clear, acceptance criteria defined, dependencies identified, estimated, small enough to complete in one sprint, and has business value. DoR prevents starting work on unclear items, reducing rework and delays. It's a team agreement, not a Scrum requirement."},
        {"instruction": "What is the Definition of Done?", "input": "", "output": "The Definition of Done is a formal description of the state of the Increment when it meets the quality measures required for the product. It creates transparency and shared understanding. If a Product Backlog item doesn't meet the DoD, it can't be released or presented at the Sprint Review. The entire Scrum Team must adhere to it. Examples: code reviewed, tests passed, documentation updated, deployed to staging, acceptance criteria met."},
        {"instruction": "What is a user story?", "input": "", "output": "A user story is a short, simple description of a feature from the user's perspective. Format: 'As a [type of user], I want [some goal], so that [some reason]'. It's a placeholder for conversation, not a detailed specification. Good stories follow INVEST criteria and include acceptance criteria. Stories focus on user value, not technical implementation. They're estimated in story points and broken into tasks during sprint planning."},
        {"instruction": "What are acceptance criteria?", "input": "", "output": "Acceptance criteria define the conditions a user story must meet to be considered complete. They're specific, testable, and written from the user's perspective. Format: 'Given [context], when [action], then [result]'. They clarify requirements, guide development, form the basis for tests, and prevent scope creep. Each story should have multiple acceptance criteria covering happy paths and edge cases. They're agreed upon during backlog refinement."},
        {"instruction": "What is the INVEST criteria?", "input": "", "output": "INVEST is a checklist for good user stories: Independent (can be developed separately), Negotiable (not a fixed contract), Valuable (delivers value to users/customers), Estimable (team can size it), Small (fits in one sprint), Testable (has clear acceptance criteria). If a story fails INVEST, split or refine it before bringing it into a sprint. INVEST helps teams write better stories and avoid common pitfalls."},
        {"instruction": "How do you split a user story?", "input": "", "output": "Split stories using these strategies: 1) By workflow steps (each step becomes a story), 2) By business rule variations (different rules = different stories), 3) By type of user (admin vs regular user), 4) By CRUD operations (create, read, update, delete separately), 5) By happy path vs edge cases, 6) By platform (web, mobile, API). Keep each piece valuable and testable. Splitting makes stories small enough to complete in one sprint."},
        {"instruction": "What is a task in Scrum?", "input": "", "output": "A task is a unit of work needed to complete a user story, typically estimated in hours (not story points). Tasks are identified during sprint planning and make up the Sprint Backlog. They're technical activities like 'design database schema', 'implement API', 'write unit tests'. Tasks are owned by individual developers, unlike stories which are owned by the team. Tasks should be small enough to complete in a day. They help track daily progress."},
    ]
    
    # ===== COMMON CHALLENGES & SOLUTIONS (30 examples) =====
    challenges_data = [
        {"instruction": "How do you handle scope creep?", "input": "", "output": "Scope creep is managed by: 1) Clear Definition of Done and acceptance criteria, 2) Product Owner prioritizing the backlog, 3) Timeboxed sprints with fixed goals, 4) Change requests go through the Product Owner, 5) New items go to the Product Backlog (not current sprint), 6) Trade-off discussions if urgent changes are needed. Agile embraces change, but controls it through prioritization and timeboxing."},
        {"instruction": "What if the team can't finish the sprint?", "input": "", "output": "If the team realizes they can't complete the Sprint Goal: 1) Discuss options early (not at sprint end), 2) The Product Owner may descope low-priority items, 3) Focus on completing highest-value items, 4) Unfinished items return to the Product Backlog for re-estimation, 5) Learn from it in the retrospective. Don't extend the sprint - instead, improve estimation and planning. It's a learning opportunity, not a failure."},
        {"instruction": "What if the sprint goal becomes obsolete?", "input": "", "output": "If the Sprint Goal becomes obsolete (e.g., market change, technical impossibility), only the Product Owner can cancel the sprint. This is rare and drastic. When cancelled: completed items are reviewed, potentially releasable items are accepted, incomplete items are re-estimated and returned to the Product Backlog. A new sprint planning starts immediately. The goal should rarely change mid-sprint - if it does, inspect why."},
        {"instruction": "How do you handle dependencies between teams?", "input": "", "output": "Dependencies are managed by: 1) Identifying them early in planning, 2) Sequencing work to minimize dependencies, 3) Using Scrum of Scrums for coordination, 4) Creating shared Definition of Done, 5) Aligning sprint cadences, 6) Using features teams (cross-component) instead of component teams, 7) Visualizing dependencies on a program board. Dependencies slow delivery - minimize them through architecture and team structure."},
        {"instruction": "What if stakeholders keep changing priorities?", "input": "", "output": "Frequent priority changes are managed by: 1) Product Owner owning prioritization decisions, 2) Timeboxed sprints protecting current work, 3) Changes go to Product Backlog for next sprint, 4) Clear communication about trade-offs, 5) Regular stakeholder reviews (sprint reviews), 6) Visualizing the cost of context switching. If priorities change constantly, inspect why - it may indicate unclear vision or poor stakeholder management."},
        {"instruction": "How do you handle technical debt?", "input": "", "output": "Technical debt is managed by: 1) Including refactoring in the Definition of Done, 2) Allocating time each sprint to address debt (10-20% of capacity), 3) Making debt visible in the Product Backlog, 4) Discussing it in retrospectives, 5) Using spikes to investigate solutions, 6) Measuring debt through code quality metrics. Ignoring debt slows future sprints; managing it maintains sustainable pace and quality. Balance new features with debt reduction."},
        {"instruction": "What if the team is too large?", "input": "", "output": "If the team exceeds 10 people: 1) Split into multiple Scrum Teams working on the same product, 2) Each team should be cross-functional, 3) Align sprint cadences for coordination, 4) Use Scrum of Scrums for daily coordination, 5) Ensure shared Product Backlog and Product Owner, 6) Coordinate through a common Definition of Done. Large teams have communication overhead - splitting improves focus and velocity."},
        {"instruction": "What if the team lacks skills?", "input": "", "output": "Skill gaps are addressed by: 1) Cross-training within the team, 2) Pair programming to share knowledge, 3) Hiring or contracting specialists, 4) Investing in training and conferences, 5) Using mob programming for complex tasks, 6) Adjusting the Definition of Done to match current capabilities (temporarily). Long-term, teams should become T-shaped (deep expertise plus broad skills). Skill gaps are a retrospective topic."},
        {"instruction": "How do you handle remote teams?", "input": "", "output": "Remote teams succeed by: 1) Over-communicating through chat, video, and documentation, 2) Using collaborative tools (Miro, Mural, Jira), 3) Establishing working agreements (core hours, response times), 4) Recording meetings for async viewing, 5) Scheduling regular video standups, 6) Building rapport through virtual social events, 7) Using digital whiteboards for planning. Remote work requires intentional communication and trust."},
        {"instruction": "What if the Product Owner is unavailable?", "input": "", "output": "An unavailable Product Owner slows the team. Solutions: 1) Delegate decisions to a proxy (with clear authority), 2) Schedule regular office hours for the team, 3) Use async communication (Slack, email) for quick questions, 4) Ensure the backlog is well-refined before sprint planning, 5) Empower the team to make small decisions within guardrails, 6) Escalate to stakeholders if the PO is consistently unavailable. The PO must be available enough to unblock the team."},
        {"instruction": "What if the Scrum Master is too directive?", "input": "", "output": "A directive Scrum Master undermines self-organization. They should: 1) Coach rather than command, 2) Ask questions instead of giving answers, 3) Facilitate discussions rather than dictate solutions, 4) Remove impediments rather than assign tasks, 5) Protect the team rather than control them, 6) Model Agile values and principles. The Scrum Master is a servant-leader who enables the team, not a manager who directs them. Coach them on facilitation skills."},
        {"instruction": "How do you handle conflicts within the team?", "input": "", "output": "Conflicts are addressed by: 1) Addressing them early and directly, 2) Focusing on issues, not personalities, 3) Using retrospectives to discuss openly, 4) Encouraging empathy and active listening, 5) Establishing team working agreements, 6) Involving the Scrum Master as a mediator if needed, 7) Escalating to management if unresolved. Healthy conflict improves decisions; toxic conflict destroys teams. Create psychological safety for open discussion."},
        {"instruction": "What if daily standups become status meetings?", "input": "", "output": "Standups should be planning meetings, not status reports. Fix this by: 1) Focusing on the Sprint Goal, not individual tasks, 2) Walking the board (reviewing items, not people), 3) Keeping it to 15 minutes, 4) Encouraging team discussion, not reporting to the Scrum Master, 5) Having the team facilitate (rotate facilitator), 6) Taking detailed discussions offline. The standup is for the team to plan the next 24 hours, not for managers to get updates."},
        {"instruction": "How do you improve sprint retrospectives?", "input": "", "output": "Improve retrospectives by: 1) Varying the format (Start-Stop-Continue, 4Ls, Sailboat), 2) Ensuring psychological safety (no blame), 3) Focusing on 1-3 actionable improvements, 4) Following up on previous action items, 5) Using data (metrics, trends), 6) Rotating facilitators, 7) Timeboxing strictly, 8) Celebrating successes. Retrospectives should result in concrete experiments for the next sprint, not vague wishes. They're the most important event for improvement."},
        {"instruction": "What if the team doesn't follow the Definition of Done?", "input": "", "output": "If the team skips DoD criteria: 1) Discuss why in the retrospective, 2) Inspect if the DoD is realistic, 3) Make DoD visible (poster, checklist), 4) Automate DoD checks (CI/CD, automated tests), 5) Have the team hold each other accountable, 6) Escalate to the Scrum Master if needed. The DoD is a team agreement - if it's not followed, either the team doesn't believe in it (needs discussion) or they need help meeting it (needs support)."},
        {"instruction": "How do you handle underperforming team members?", "input": "", "output": "Underperformance is addressed by: 1) Private, empathetic conversations to understand root causes, 2) Providing coaching and mentoring, 3) Adjusting workload or responsibilities, 4) Setting clear expectations and goals, 5) Offering training or resources, 6) Involving HR if it's a behavioral issue, 7) Making tough decisions if performance doesn't improve. Agile teams support each other - underperformance is a team problem, not just an individual one."},
        {"instruction": "What if velocity keeps decreasing?", "input": "", "output": "Decreasing velocity indicates a problem. Investigate: 1) Technical debt accumulating, 2) Team morale or burnout, 3) Increasing complexity or scope, 4) Too many interruptions or meetings, 5) Skill gaps or turnover, 6) Poor estimation (stories getting larger). Use retrospectives to identify root causes. Velocity is a diagnostic tool - when it drops, inspect and adapt. Don't pressure the team to 'work harder' - fix the system."},
        {"instruction": "How do you handle urgent bugs during a sprint?", "input": "", "output": "Urgent bugs are handled by: 1) Assessing severity (is it truly urgent?), 2) The Product Owner prioritizes the bug against sprint work, 3) If critical, pull it into the sprint and descope equivalent work, 4) If not critical, add to Product Backlog for next sprint, 5) Track bugs as backlog items with estimates, 6) Allocate capacity for bugs in future sprints (10-20%). Don't let bugs derail the sprint - prioritize and trade-off."},
        {"instruction": "What if stakeholders don't attend sprint reviews?", "input": "", "output": "Low stakeholder attendance is a problem. Fix it by: 1) Making reviews valuable (demos, not presentations), 2) Scheduling at convenient times, 3) Sending invites early with clear agendas, 4) Showing the impact of their feedback, 5) Recording reviews for async viewing, 6) Following up with written summaries, 7) Escalating to management if engagement is critical. Stakeholder feedback is essential - if they don't attend, the team is building in the dark."},
        {"instruction": "How do you measure Agile success?", "input": "", "output": "Agile success is measured by: 1) Customer satisfaction and business value delivered, 2) Time to market (lead time, cycle time), 3) Quality (defect rates, production incidents), 4) Team health (morale, retention, sustainability), 5) Predictability (velocity trends, forecast accuracy), 6) Adaptability (response to change, learning speed). Avoid vanity metrics (lines of code, hours worked). Focus on outcomes, not outputs. Measure what matters to the business and team."},
        {"instruction": "What if the team is burned out?", "input": "", "output": "Burnout is addressed by: 1) Inspecting workload and reducing commitments, 2) Ensuring sustainable pace (no overtime), 3) Improving work-life balance (flexible hours, time off), 4) Addressing root causes (too many meetings, unclear goals, toxic culture), 5) Celebrating successes and recognizing contributions, 6) Providing growth opportunities, 7) Involving HR or management if needed. Burnout is a system problem, not an individual weakness. Agile promotes sustainable development."},
        {"instruction": "How do you handle resistance to Agile?", "input": "", "output": "Resistance is addressed by: 1) Understanding the root cause (fear, misunderstanding, past failures), 2) Starting with willing teams (don't force it), 3) Demonstrating value through pilot projects, 4) Providing training and coaching, 5) Celebrating early wins, 6) Involving resisters in the transformation, 7) Being patient - culture change takes time. Agile is a mindset, not a process - you can't mandate it. Lead by example and show results."},
        {"instruction": "What if the team doesn't self-organize?", "input": "", "output": "Self-organization develops over time. Help it by: 1) Coaching the team on self-management, 2) Removing command-and-control behaviors (from managers or Scrum Master), 3) Empowering the team to make decisions, 4) Establishing clear boundaries and guardrails, 5) Encouraging experimentation and learning from failures, 6) Building trust and psychological safety. Self-organization doesn't happen overnight - it requires patience, coaching, and a supportive environment."},
        {"instruction": "How do you handle distributed time zones?", "input": "", "output": "Distributed time zones are managed by: 1) Establishing overlapping core hours for collaboration, 2) Using async communication (chat, documentation) for non-urgent matters, 3) Recording meetings for async viewing, 4) Rotating meeting times to share the burden, 5) Using collaborative tools (Miro, Confluence, Jira), 6) Building rapport through virtual social events, 7) Being respectful of personal time. Time zones require intentional communication and flexibility."},
        {"instruction": "What if the Product Backlog is too large?", "input": "", "output": "A large backlog is managed by: 1) Regularly pruning obsolete items, 2) Keeping only the top items refined and ready, 3) Using themes or epics for high-level grouping, 4) Archiving old items (don't delete - just move them), 5) Focusing on the next 2-3 sprints in detail, 6) Using roadmap planning for longer-term vision. The backlog should be a living document, not a dumping ground. Less is more - focus on what's important now."},
        {"instruction": "How do you handle changing requirements mid-sprint?", "input": "", "output": "Changing requirements mid-sprint should be minimized. If absolutely necessary: 1) The Product Owner and team discuss the impact, 2) If it endangers the Sprint Goal, negotiate removing equivalent work, 3) Add new items to the Product Backlog (not Sprint Backlog) for future sprints, 4) Only add to current sprint if it's critical and the team agrees. Protect the Sprint Goal! Changes should go through the Product Owner, not directly to developers."},
        {"instruction": "What if the team is siloed?", "input": "", "output": "Silos are broken by: 1) Encouraging pair programming and mob programming, 2) Rotating tasks and responsibilities, 3) Using T-shaped skills (deep expertise plus broad understanding), 4) Holding team discussions (not sub-group meetings), 5) Establishing shared goals and Definition of Done, 6) Celebrating team successes (not individual heroes). Silos reduce collaboration and create bottlenecks. Build a culture of shared ownership and collective responsibility."},
        {"instruction": "How do you handle legacy code in Agile?", "input": "", "output": "Legacy code is managed by: 1) Adding automated tests before refactoring (characterization tests), 2) Refactoring incrementally (boy scout rule: leave it better than you found it), 3) Using the strangler fig pattern (replace pieces gradually), 4) Allocating time each sprint for debt reduction, 5) Documenting decisions and architecture, 6) Investing in CI/CD to catch regressions. Legacy code is a reality - manage it through continuous improvement, not big rewrites."},
    ]
    
    # Combine all data
    all_data = identity_data + agile_fundamentals + scrum_data + kanban_data + estimation_data + challenges_data
    
    # Add variations to increase dataset size
    expanded_data = []
    for item in all_data:
        expanded_data.append(item)
        
        # Add "Question:" prefix variation
        variation = item.copy()
        variation["instruction"] = f"Question: {item['instruction']}"
        expanded_data.append(variation)
        
        # Add "Can you tell me" variation for some
        if len(item["instruction"].split()) > 3:
            variation2 = item.copy()
            variation2["instruction"] = f"Can you tell me {item['instruction'].lower()}"
            expanded_data.append(variation2)
    
    return expanded_data

def main():
    print("="*60)
    print("Generating Agile Project Management Training Data")
    print("="*60)
    
    data = generate_agile_training_data()
    
    output_path = "./data/training/agile_pm_qa.json"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"\n✓ Generated {len(data)} training examples")
    print(f"✓ Saved to {output_path}")
    
    # Convert to Hugging Face dataset
    dataset = Dataset.from_list(data)
    dataset.save_to_disk("./data/training/agile_pm_dataset")
    print(f"✓ Dataset saved to ./data/training/agile_pm_dataset")
    
    print("\n" + "="*60)
    print("Next steps:")
    print("1. Update config.yaml to use agile_pm_dataset")
    print("2. Run: python scripts/03_train_lora.py")
    print("3. Run: python scripts/04_merge_model.py")
    print("4. Restart Mini Me!")
    print("="*60)

if __name__ == "__main__":
    main()